config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :destroy, :new]
  resources :messages, only: [:create, :new]
  root to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id                   :integer          not null, primary key
#  content              :string
#  number_of_characters :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  sender_id            :integer
#  receiver_id          :integer
#

class Message < ApplicationRecord
    validates :content, :sender_id, :receiver_id, presence: true
    attr_reader :body
    attr_reader :receiver
    def body=(content)
        self.content = content
        self.number_of_characters = content.length
    end

    def receiver=(receiver)
        @receiver = receiver
        user = User.find_by(username: receiver)
        if(user)
            self.receiver_id = user.id
        else
            nil
        end
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :integer          not null, primary key
#  username             :string
#  password             :string
#  address              :string
#  session_token        :string
#  remaining_emails     :integer
#  remaining_characters :integer
#

class User < ApplicationRecord
    validates :username, :password, :address, presence: true
    validates :username, :address, uniqueness: :true

    has_many :sent_messages,
        primary_key: :id,
        foreign_key: :sender_id,
        class_name: :Message

    has_many :received_messages,
        primary_key: :id,
        foreign_key: :receiver_id,
        class_name: :Message

    after_initialize :ensure_session_token, :ensure_messages
    def ensure_messages
        self.remaining_characters ||= 200
        self.remaining_emails ||= 5
    end
    def ensure_session_token
        self.session_token ||= rand(255)
    end

    def reset_session_token!
        self.session_token = rand(255)
        self.save!
        self.session_token
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    skip_before_action :verify_authenticity_token
    def new
        @user = User.find_by(session_token: session[:session_token])

        #query the database for all the messages from the start of the calendar week
        week_start = Date.today.beginning_of_week
        @sent_messages = @user.sent_messages #.where("messages.created_at > ':week_start'",week_start: week_start)
        @remaining_messages = 5 - @sent_messages.length
        if @remaining_messages > 0
            @remaining_characters = 200 - @sent_messages.inject(0){ |total, msg| total + msg.number_of_characters}
            if @remaining_characters > 0
                @received_messages = @user.received_messages #.sort{|msg1, msg2| msg1.created_at <=> msg2.created_at}
                render :new
            else
                render json: {error: "no more characters left"}
            end
        else
            render json: {error: "out of emails"}
        end
    end

    def create
        @message = Message.new(message_params)
        if @message.save
            redirect_to new_message_url
        else
            render json: {error: @message.errors.full_messages }
        end
    end

    private
    def message_params
        params.require(:message).permit(:receiver, :body, :sender_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :verify_authenticity_token

    def create
        @user = User.find_by(username: user_params[:username]);
        if !@user
            render json: {errors: "no user with that username"}, status: 422;
        elsif @user.password == user_params[:password]
            session[:session_token] = @user.session_token
            redirect_to new_message_url
        else
            render json: {errors: "incorrect password"}, status: 422
        end
    end

    def new
        if(User.find_by(session_token: session[:session_token]))
            redirect_to new_message_url
        else
            render :new
        end
    end

    def destroy
        @user = User.find_by(session_token: session[:session_token])
        @user.reset_session_token!
        session[:session_token] = nil
        redirect_to new_user_url
    end

    private
    def user_params
        params.require(:user).permit(:username,:password,:address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verify_authenticity_token
    def create
        @user = User.new(user_params)
        if @user.save
            session[:session_token] = @user.session_token
            redirect_to new_message_url
        else
            render json: {errors: @user.errors.full_messages}, status: 422
        end
    end
    def new
        if(User.find_by(session_token: session[:session_token]))
            redirect_to new_message_url
        else
            render :new
        end
    end
    private
    def user_params
        params.require(:user).permit(:username,:password,:address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FigLoans</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/limit_reached.html.erb
<h1> Hey It Worked </h1>

app/views/messages/new.html.erb
<h1>Greetings <%= @user.username %> </h1>
<h2> You have <%= @remaining_messages %> messages left and <%= @remaining_characters %> characters remaining </h2>
<form action="<%= session_url%>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Log Out">
</form>
<ul>
    <% @received_messages.each do |msg|%>
        <%= msg.content %>
    <% end%>
</ul>
<form action="<%= messages_url %>" method="POST" id="messageform">
    <input type="hidden" value="<%= @user.id %>" name="message[sender_id]">
    <label> To:
        <input type="text" name="message[receiver]">
    </label>
    <label>Body:
        <input type="text" name="message[body]">
    </label>
    <input type="submit" value="Send">
</form>

app/views/users/new.html.erb
<h1>Welcome to The Interstate Messaging System! </h1>
<p>Please fill out the form below and click the submit button when it appears to create your account or <a href="<%= new_session_url %>">sign in</a></p>
<form class="user-form" action="<%= users_url %>" method="POST">
    <label> <strong>Username</strong>
        <span id="usernameErrors"></span>
        <input type="text" name="user[username]">
    </label>
    <label><strong>Password</strong>
        <span id="passwordErrors"></span>
        <input type="password" name="user[password]" oninput="passwordCheck(this.value)" onchange="errorsDisplay()">
    </label>
    <label><strong>Address</strong>
        <span id="addressErrors"></span>
        <input type="text" name="user[address]">
    </label>
    <input id="submit-btn" type="submit" value="submit">
</form>